name: ci

on:
  push:
    branches:
      - ci-experiment
  pull_request:
    branches:
      - ci-experiment

jobs:
  Contracts:
    name: Smart contracts
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: install node.js
        uses: actions/setup-node@v6
        with:
          node-version: '>=18.0.0'

      - name: install dependencies
        run: npm ci --legacy-peer-deps

      - name: compile contracts
        run: npx hardhat compile

      - name: runs the tests in test directory
        run: npx hardhat test

  Frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: install node.js
        uses: actions/setup-node@v6
        with:
          node-version: '>=18.0.0'

      - name: install frontend dependencies
        run: |
          cd frontend
          npm ci --legacy-peer-deps

      - name: lint
        run: |
          cd frontend
          npm run lint

      - name: build
        run: |
          cd frontend
          npm run build
          

  Backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: install node.js
        uses: actions/setup-node@v6
        with:
          node-version: '>=18.0.0'

      - name: install backend dependencies
        run: |
          cd backend
          npm ci --legacy-peer-deps

      - name: build
        run: |
          npm run

        
        



        
      



