name: ci

on:
  push:
    branches:
      - ci-experiment
  pull_request:
    branches:
      - ci-experiment

jobs:
  contracts:
    name: Smart contracts
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: install dependencies
        run : npm ci





